<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Posting Job Paket pilih Freelancer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f3018985-5b73-44e7-aa51-24abb91f5dd8</testSuiteGuid>
   <testCaseLink>
      <guid>9da1a844-27f3-4ca3-8460-9cda9a258e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/PAKET JOB/STA-JPPRIV-001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d3dfb7d-0f00-4c80-b013-1b66219b8118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03db5747-3ddc-472d-9613-ab061f0ab701</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd9d02f0-5a06-45f1-815c-af45b5955553</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7b05560-66a8-4c47-b2d0-8c84e0687e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0c1bda1-7144-4186-8fc0-c883069e14b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bf209d9-a7bf-47ca-8147-fcb536f3cc3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c27e4cb-4139-4459-b2b1-8feb1d60ae37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32444ef0-f46c-46e8-913c-89d55bb2d6af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f809e03f-d5bc-4d72-b9db-962f9d374507</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>609fa8fe-feee-440b-b377-400d075ad1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16489ca7-d5e3-422b-ba15-d189f322efc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b41f3e2-e771-49ca-873b-d05dfa28a104</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1945a0-d7a1-457b-af28-ea62b8197887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>810d5aa7-be34-43c3-b0e1-062dfc0eb468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30fec6d0-2ceb-4151-b191-00ff6c49395a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dbda608-5a6d-4b84-bf79-0ff50f40cff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/JAR-APD-001</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ec859306-003d-4a6c-be0a-d55c8d93f8d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/PAKET JOB/STA-VALJ-002</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
