<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Posting Job Public</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>aaee3c58-c7ae-4b46-bd1d-d1252bed24ff</testSuiteGuid>
   <testCaseLink>
      <guid>da5cfd30-ba70-4c39-af6d-a26c753d9447</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/POST JOB/Posting Job Public</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd87b9b-26c5-45a8-8af9-3fc5287cf3a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01ac20ac-2663-4b24-bfbf-2a52eb38ae41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4096b10-d133-40d4-bb7c-85b925778ee9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc8d778-f29e-41c1-9cbe-589a89ecd6f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b1a836f-4a0e-42e0-9576-ebd1dcc623f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beaebab6-f06e-47a3-851e-4b6c44fe80ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14f87ab2-849a-4b95-b573-fb408c02e59c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ae905f-dafe-4e4c-90bf-dbc34e8b7755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f79365-6537-4eee-b68a-5492f6cdc4ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e53d4b9-296c-41a6-a6ed-63437a51e4ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/Approve Job Public</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e3d7f7e-5e45-4fd3-955b-99995b11ac3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12f9f01f-9b66-4dc5-a192-2432aa15606c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/POST JOB/Validasi Job Berhasil Diapprove</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8768227e-0d4a-44b3-b86c-0e10b39a37c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
