<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Posting Job Paket</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b5a6974e-8fda-4544-8092-09e715a7a645</testSuiteGuid>
   <testCaseLink>
      <guid>99b073a9-9379-4e3b-9841-77645b5b94b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/PAKET JOB/PAKET JOB TIDAK PILIH FREELANCER</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ee3ac98-df57-4927-bf6a-e44448678ad7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb30c53-7bbe-495d-8d7c-564f5686df12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb19c40e-e682-4833-9776-0eed4e7a48f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d59494c1-0115-4549-8dd1-1a86491655c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468b542e-8785-4982-839e-bdc073a967fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec2654f-6a7f-4323-90fb-a84d5a2a09b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6bf8c89-f3f7-4b59-930a-fef320d359af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caef87f3-2623-43f7-909c-e94dc917241f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22b1cd06-f0e5-46d6-82f4-1228c2965729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d4d3ceb-5390-49a0-98d8-11c6b83e3959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc8175b-99d3-4329-a9e1-577946b6c08c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d052693-2a5c-4e51-a457-e695d2b9276a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/Approve Transfer Payment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>07f3cb18-760c-41aa-aa98-a7ee2835b131</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/Approve Job Paket</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
