<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Posting Job Paket Tidak pilih Freelancer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b5a6974e-8fda-4544-8092-09e715a7a645</testSuiteGuid>
   <testCaseLink>
      <guid>606a9e6d-f437-4459-a943-c0aa6716d438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/PAKET JOB/STA-JPPUB-001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ee3ac98-df57-4927-bf6a-e44448678ad7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>273fe60a-081c-4df3-aa81-9a78872d080e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d59ec8-8de2-4b56-af70-fb454a494866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb30c53-7bbe-495d-8d7c-564f5686df12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb19c40e-e682-4833-9776-0eed4e7a48f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d59494c1-0115-4549-8dd1-1a86491655c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc8175b-99d3-4329-a9e1-577946b6c08c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec2654f-6a7f-4323-90fb-a84d5a2a09b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6bf8c89-f3f7-4b59-930a-fef320d359af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468b542e-8785-4982-839e-bdc073a967fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d4d3ceb-5390-49a0-98d8-11c6b83e3959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caef87f3-2623-43f7-909c-e94dc917241f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22b1cd06-f0e5-46d6-82f4-1228c2965729</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9f6e116-c278-49d0-b0c6-cbf7201cf854</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/JAR-APD-001</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bac00e3f-b1d9-45d3-995f-78cafa043efe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/PAKET JOB/STA-VALJ-002</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
