<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Posting Kontes Desain Logo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7dbfa10b-0bc5-4acf-97d9-350e81c6053d</testSuiteGuid>
   <testCaseLink>
      <guid>58f9b252-8e77-45f3-bfd8-2634f99a438c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/ORDER KONTES/Order Kontes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc51c400-c577-4410-b8e0-da83f32c6ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>042d3b7a-0c64-4e38-82f2-3813e738bb08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7edeea1e-38a3-4383-ac12-f795a1d5b7d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a96d50ca-3a7f-46a6-aeaa-ff0700503b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69df6d8a-4e94-4244-99b0-745816a0661a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4c436d-7722-4bf6-8d64-ddb6d964f66e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed51062-1391-4411-822c-55a7becda4cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7c27db-a0d5-4a4c-92bf-eff4de130e7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a1c19bf-f43b-4243-b9b5-4f3266a441e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452e92c8-da71-40f4-83a7-9c91f72a0405</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce86e29-82d3-470e-a932-a42057b71b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b428c94e-a672-4667-ab8f-bea1563b06a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7d09fb4-3c9b-4da4-88d3-80f453345b3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3482b292-de67-4455-816b-58aa0fa2dae0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb8adbe4-e9ef-423c-9c39-9b25d268f16d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JARVIS/Approve Kontes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d58777-2b2a-4412-93e9-8c5709d67e35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb07d62b-f498-4808-a5ce-33d387e2bc2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/THANOS/ORDER KONTES/Validasi Kontes telah terbuat</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
